# ==================================== LIST OF PROXIES =========================================
proxies = {
    'key1': True,
    'key2': True,
    'key3': True,
    'key4': True,
    'key5': True,
    'key6': True,
    'key7': True,
    'key8': True,
    'key9': True,
    'key10': True,
    'key11': True,
    'key12': True,
    'key13': True,
    'key14': True,
    'key15': True,
    'key16': True,
    'key17': True,
    'key18': True,
    'key19': True,
    'key20': True,
    'key21': True,
    'key22': True,
    'key23': True,
    'key24': True,
    'key25': True,
    'key26': True,
    'key27': True,
    'key28': True,
    'key29': True,
    'key30': True,
    'key31': True,
    'key32': True,
    'key33': True,
    'key34': True,
    'key35': True,
    'key36': True,
    'key37': True,
    'key38': True,
    'key39': True,
    'key40': True,
    'key41': True,
    'key42': True,
    'key43': True,
    'key44': True,
    'key45': True,
    'key46': True,
    'key47': True,
    'key48': True,
    'key49': True,
    'key50': True
}

# ==================================== LIST OF SHOPS ========================================= 
shops = [
    "ajio_in",
    "allensolly",
    "amama",
    "amazon_in",
    "americaneagle",
    "andindia",
    "attitudist",
    "azafashions",
    "beardo",
    "beyoung",
    "biba",
    "boatlifestyle",
    "boddess",
    "campussutra",
    "candere",
    "carltonlondon",
    "celio",
    "chkokko",
    "clovia",
    "exclusivelane",
    "fabindia",
    "fastrack",
    "firstcry",
    "flipkart_in",
    "fossil",
    "gasjeans",
    "globaldesi",
    "hautesauce",
    "hidesign",
    "hopscotch",
    "lenovo",
    "levis",
    "libas",
    "moglix",
    "myntra",
    "nestasia",
    "nilkamalfurniture",
    "nykaa_in",
    "nykaafashion_in",
    "only",
    "pantaloons",
    "portronics",
    "realme",
    "sassafras",
    "selectedhomme",
    "shopclues_in",
    "shyaway",
    "snapdeal_in",
    "suta",
    "tatacliqpalette",
    "tatacliq_in",
    "titan",
    "uniqloindia",
    "vaaree",
    "wforwoman",
    "wildcraft"
]
